# Generated by Django 2.2.9 on 2020-07-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='special_instructions',
            field=models.CharField(blank=True, default='None', help_text='Any special requests', max_length=500, null=True),
        ),
    ]
